SimenB/stylint

README.md

Alphabetized config options and explanations

---

index.js
src/done.js

add option to toggle emoji on or off (if on, will display differently depending on OS)
by default it will be set to false

add toggle for emoji output

---

src/checks/valid.js
test/test.js

fix issue where attribute selectors cause the valid check to fail

Attribute selectors

---

contributing.md

add a contrib file

---

README.md
index.js
src/checks/namingConvention.js
test/test.js

add the namingConventionStrict option

Naming convention strict

---

src/checks/namingConvention.js
styl/ui.styl
test/test.js

to prevent namingConvention throwing false positives due to things like font names, don't test against the whole line, but just the property

add more tests to namingConvention

---

src/checks/borderNone.js
styl/ui.styl
test/test.js

addressing this issue: https://github.com/rossPatton/stylint/issues/78

make border none check style agnostic

---

index.js
src/checks/borderNone.js
src/checks/valid.js
src/data/valid.json
styl/ui.styl
test/test.js

see this thread: https://github.com/rossPatton/stylint/issues/61

fix several issues with duplicates and valid checks

---

.stylintrc
index.js
src/checks/keyframeEnd.js
src/checks/keyframeStart.js
src/checks/valid.js
src/checks/zeroUnits.js
src/data/valid.json
src/test.js
styl/testKeyframes.styl
test/test.js

in this pr:
sneaking in fix for outlook table styling
fix this issue: https://github.com/rossPatton/stylint/issues/95
fix this issue: https://github.com/rossPatton/stylint/issues/96

Keyframes hotfixes

---

.gitignore
.stylintrc
package.json
src/utils/setConfig.js
test/test.js

New PR against `develop` instead of `master`

Allow comments in .stylintrc

---

README.md

Seems like a copy-paste error :smile:

Fix link to grunt-plugin

---

package.json

Run linting before tests

---

src/core/done.js
src/core/reporter.js
test/test.js

If no errors or warnings, don't print anything to the console

---

src/core/done.js
test/test.js

Return errors and warnings in addition to message and exitcode from done

---

.codeclimate.yml
.eslintignore
test/test.js

Saw you recently did some fixing of it, thought to complete the process :smile: 
I disabled the `no-undefined` rule for the tests. I could switch usage from `undefined` to `null` instead perhaps?
Also, what about setting up travis or one of its brethren to automatically build PRs? I can see from the coverage badge that code climate is set up, but AFAIK they don't build PRs, do they?
Found [this](http://docs.codeclimate.com/article/213-github-pull-request-integration) which seems to indicate something, but I'm unsure if it runs `npm test` or what.

Add linting to tests

---

README.md

Because `README.md` does not match `core/config.js`

Update default options

---

src/checks/commentSpace.js

```stylus
// This sort of thing (empty line below 
// with trailing-space trimmed)
//
// ...shouldn't trigger a warning. Mmmmkay?
```

Allow empty commented lines.

---

src/data/valid.json

I can add a test for this as well, if desired.

Add stroke and stroke-width as valid CSS properties. Fixes #254

---

README.md

I've created JSON formatted reporter for my stylint JetBrains plugin, maybe someone will find it useful

add stylint-json-reporter to readme

---

src/checks/efficient.js

wrong variable was used and conditions were never met

fix 'efficient' check

---

src/core/done.js
test/test.js

Set exit code to 1 if over maxWarning or maxErrors

---

README.md

from https://github.com/rossPatton/stylint/pull/223/commits/74c47fccecd6068af6db615eb79b38077b6138d8

explain `exclude` option in README

---

src/data/valid.json

Added meta to whitelist.

---

README.md

Unless there's a reason for the lowercase 'l'

ClI -> CLI

---

src/core/state.js

Fixes #324 
Please do a release soon on this 😄 
(accidentally targeting master, but as it's even with develop, shouldn't really matter)

Initialize `exclude` array in `state`

---

src/core/done.js

Concat message before checking if it is truthy

---

package.json

Also bumped it to latest patch version

Remove eslint from dependencies

---

.eslintrc
package.json
src/core/cache.js
src/core/done.js
src/core/init.js
src/core/parse.js
src/core/reporter.js
src/utils/msg.js
src/utils/resetOnChange.js
test/.eslintrc
test/core/reporter.test.js
test/test.js

Missing tests and grouping by file.
The responsibility of that should be in the reporter, for now I just deleted it from `done`

Don't use `this` in reporter

---

.stylintrc
src/checks/commaSpace.js
src/checks/commentSpace.js
src/checks/mixed.js
src/checks/parenSpace.js
src/checks/quotePref.js
src/checks/trailingWhitespace.js
src/checks/valid.js
src/core/cache.js
src/core/config.js
src/core/done.js
src/core/lint.js
src/core/parse.js
src/core/reporter.js
src/core/setState.js
src/utils/countSeveritiesInMessages.js
src/utils/msg.js
test/core/done.test.js
test/core/reporter.test.js
test/test.js
test/utils/countSeveritiesInMessages.test.js

Includes #367, so either that should be merged first, or take a look at the second commit directly

Restructure message obj

---

bin/stylint
index.js
src/core/cache.js
src/core/done.js
src/core/index.js
src/core/init.js
src/core/lintString.js
src/core/parse.js
src/core/transformMessages.js
src/utils/resetOnChange.js
test/core/done.test.js
test/core/transformMessages.test.js
test/test.js

See #161 
I created a V2 branch, so we can make breaking changes in there, then merge into develop when we think it's done. Mostly to allow `develop` to still receive other changes.
Contains changes from #273 as well, will rebase once that's merged

Lint string

---

README.md

Closes https://github.com/SimenB/stylint/issues/411

README.md: Fix typo in ``extendPref`` example
