- README.md
Added `'BEM'` to the heading.
Corrected `'lowercase-underscore'` to `'lowercase_underscore'`.
> Corrected namingConvention documentation

- src/data/valid.json
pointer-events and interpolation-mode added to valid.json whitelist
> Add new rules to valid whitelist

- index.js
- package.json
Hi, Absolutely loving this linter!
I've come across the need to have an absolute path for my config file, which doesn't currently work as the `process.cwd()` gets automatically prepended to the config path.
**Ideal usage:** `stylint foo.styl -c /Users/jack/.stylintrc`
This pull request adds a check to see if the specified config path is absolute. If it is, it uses it exactly as supplied. If it's not, it continues to use the code you had in place already.
In future, it might be nice to use node's [path.isAbsolute()](https://nodejs.org/api/path.html#path_path_isabsolute_path), but as it was only just released with node 0.12, I went with something more backwards compatible.
I've not added a test for this, as your existing config tests have an outstanding `@TODO` comment. Wasn't sure whether …
> Add ability to use absolute config path

- src/done.js
Windows consoles can't render the cool Unicode emoji in the "all clear"
and "warning" logs, so we will instead render simple ASCII.
Works around #55.
> Using simple ASCII instead of Unicode for Windows

- README.md
Despite the multiple references, I missed that this toggle goes into a single line comment rather than just placed written out as is. I wrote a simple use case and code sample for when and how you would use this toggle.
> Added a simple code sample explaining @stylint off

- src/test.js
Sorry, my bad, but just realised that https://github.com/rossPatton/stylint/blob/master/src/test.js#L96 is going to be one heck of a warning message when users are using a custom defined Array
> Improve sortOrder warnings

- README.md
It looks like `indentSpaces` should be `indentPref`, this commit updates the name.
`indentSpaces` is probably a leftover from the olden days.
> Updated name of option

- src/state/keyframesStart.js
- test/test.js
Also updates to only look for `@keyframes` plural, since `@keyframe` should be considered invalid.
> Allow vendor-prefixed @keyframes

- src/checks/colors.js
- test/test.js
Currently, any id selector with the first 3 consecutive letters in `[a-f]` will fail the colors check. This PR adds an ignore regex that checks for an id selector (or variable assignment) before linting.
> Ignore id selectors in colors check

- .gitignore
- src/core/done.js
I'm currently writing a reporter, but I want to print out per error, not sorted into errors and warnings. Returning blank before the end creates lots of extra whitespace. 
This change only prints out per violation-warnings if they exist.
Difference in my reporter is 
vs.
Regarding tests: Do you have any tests on output to the console? I didn't see any, that's why I haven't written one for this change.
(Link to reporter: https://github.com/SimenB/stylint-stylish)
> Only print individual error-message if they exist

- src/core/ver.js
Noticed you change it in the source on each version-bump. This reads it out instead.
> Read current version from package.json

- README.md
I've recently switched from sass to stylus and stylint has been rather helpful. The main problem is that I'm also using webpack and is a bit tedious to run each tool separately so I've created a stylint loader for webpack (webpack loaders are similar to gulp or grunt plugins).
I want to share it with the community because maybe it can be helpful for someone else so it would be nice to add a reference in this repo README.
Thanks!
> Add stylint-loader info

- README.md
Also moved `stackedProperties` docs so the rules would be in alphabetical order.
> Docs: Fixed `trailingWhitespace` docs

- src/core/init.js
As `README.md` reflects, default value for `indentPref` is false. Instead in `init.js` you assign it to `4` if custom config for `indentPref` isn't declared.
> Set indentPref value to false by default

- src/core/done.js
- test/test.js
I think `eslint` does something similar where warnings won't give a failure exit code.  What do you think?
> Should exit code be 0 if there are warnings but no errors?

- src/checks/brackets.js
- test/test.js
With brackets set to always, my linter was failing:
```stylus
my-mixin() {
{block}
}
```
on the line with `{block}`.  From digging through the source, it seemed like something was stripping out the interpolation, and passing `'  '` to the brackets check, where it was failing.  I wasn't sure where exactly to address this, but here is my attempt.
> Brackets on always shouldn't fail if line is empty

- src/data/valid.json
Add Electrons `app-region` to valid list.
https://github.com/atom/electron/blob/master/docs/api/frameless-window.md#draggable-region
> Add app-region to valid list

- src/checks/namingConvention.js
`preferred naming convention is [object Object]` is the output in case of an object
> Fix print from namingConvention

- src/checks/prefixVarsWithDollar.js
- test/test.js
Sometimes we might use `$-` or `$_` prefix to mark private variables, such as:
```stylus
$-my-private-var = red
$_myPrivateVar = red
```
So we need the option `prefixVarsWithDollar` to accept those prefixes.
> Make option `prefixVarsWithDollar` accept `$-` or `$_` prefix.

- src/checks/leadingZero.js
The leadingZero was pretty badly broken, and this should fix it – mostly at least.
I suspect other functions that deal with potentially multiple instances in the same line (such as `parenSpace`) might be plagued with some of the same problems. 
Fixes #252, #242
> Bugfix/leading zero false-positives

- src/utils/setContext.js
Only count *either* spaces or tabs. (No crazy
mixtures within a single line indent.)
Previously any extra spacing within strings or CSS values,
would count against the indenting/context value,
which is a little bit nuts.
> Limit indent counting to beginning of line

- .travis.yml
No real reason to test for regressions outside of LTS and current.
https://github.com/nodejs/LTS/blob/master/schedule.png
> Only test on current and LTS node

- README.md
- bin/stylint
- src/core/init.js
Automatic tool like IDE plugin or CI server can depend on custom reporter. Right now user has to configure it in `.stylintrc` file. This adds configuration step or place for an error.
CLI option has the highest priority. Even if user has different reporter configured in his `.stylintrc` file the CLI will ignore it. This way he can use stylish reporter for his daily work and plugin/ci server will use whatever it needs anyway.
> Add option to set custom reporter module from CLI

- src/core/cache.js
- src/core/lint.js
- src/core/parse.js
- test/test.js
Just like ESLint and sass-lint expose rule name with error message cache. Not every reporter need to use it but will be useful to display it in editor like ESLint do. Possible future use: find automatic fix by rule name and apply it inline (alt+enter inspections in Webstorm IDE).
BTW. What's the difference between state and cache objects? Some warning message properties are on state (severity) and some are on cache (lineNo, msg, etc). Did I choose the right one?
> cache rule name with error message for reporters to use as they need

- src/checks/leadingZero.js
- test/test.js
One of PRs broke "undefined if range" tests, allowing them to pass first regex.
I've rearranged "range" tests and added few more fore brackets and spacing test. Travis should be happy now.
> Fix leading zero to pass tests

- .stylintrc
- src/core/init.js
- src/utils/getFiles.js
- src/utils/setConfig.js
To make sure everything is set in one place. Also one `setConfig()` call won't mess with async operations #264 by wiping out few properties from `this.config`. Should be more testable if all config sets are in one unit.
> Move all this.config writes to setConfig method

- src/checks/namingConvention.js
so whitespace is ignored and variables inside blocks are also checked
> fix 'namingConvention', use splitAndStrip helper

- src/checks/parenSpace.js
- test/test.js
only `myMixin(param1, param2)` and `myMixin( param1, param2 )` were recognized
handle single space `myMixin( param1, param2)` and `myMixin(param1, param2 )` too
> check missing space/parenthesis variations for parenSpace

- src/core/parse.js
I had a problem with double increment until I realized the second one is just ignored.
There are three solutions to simplify the code:
1. remove second post-increment: `this.cache.lineNo = lineNo`
2. remove the first one, and use pre-increment `this.cache.lineNo = ++lineNo`
3. make it so obvious that no one ever wonders why `this.cache.lineNo = lineNo + 1`
I like the last one best.
> simplify linoNo increment

- src/checks/duplicates.js
Cache file change within duplicates check module so we can recognize when file changes
Current tests where `this.cache.prevFile` equals `this.cache.file` never happen. This simple `lastFile` check works fine keeping all the logic within duplicates module.
> fix duplicates without globalDupe

- src/checks/commaSpace.js
- test/test.js
When comma without space was found: `wrong-mixin3( $param1, $param2,$param3 ) { }` check returned false positive.
> fix commaSpace check for mixed variants

- src/checks/quotePref.js
- test/test.js
Additional tests and refactor for:
single quote within string: "let’s"
mixed strings: '.join-strings( $content1 = "Hello!", $content2 = \'World!\' )
> Fix quote pref check

- src/checks/valid.js
- test/test.js
Added one more checking section to check standalone pseudo selectors (e.g. `:focus`, `:: -webkit-scrollbar `).
Fixes #231
> Adding a check for standalone pseudo selectors.

- src/utils/setConfig.js
Ran into an issue with our tests in a tox environment under node 0.12 where `require( 'user-home' )` was returning `null`, and we didn't have a default `.stylintrc` file defined, causing this code to fail.
> check that user-home string is actually available

- src/utils/setConfig.js
Fixes #296 
Creds to @wojciechczerniak for this, seeing that globa actually wraps minimatch, instead of always delegating to it.
My bad for not checking better!
This does expose a hole in the tests though, there ar noe tests for the exclude, and `getFiles` is mocked out in it's tests. Should probably set up som basic mock-fs based tests or something, and add them.
//cc @rossPatton
> Return minimatch instance from excludes

- .stylintrc
- src/checks/banFunctions.js
- src/checks/index.js
- src/core/config.js
- test/test.js
This is a small request to add new functionality to the linter for banning specific key words. It allows you to specify a list of key words that will get flagged in the linter when found. The use case for this is banning the use of things like `translate3d` in your application:
`"bannedFunctions": ["translateX", "translateY", "translate3d"]`
Let me know what you think @rossPatton , this would be a huge help for what we are trying to do.
> Add method for banning functions.

- package.json
- src/core/cache.js
- src/core/done.js
- src/core/lint.js
- src/core/reporter.js
- src/utils/msg.js
- src/utils/resetOnChange.js
- test/test.js
Fixes #357 
Also a start for #356
It's mostly a subset of #274, so it's probably a bit rough around the edges
/cc @wojciechczerniak
> Drop separate err and warnings on cache

- src/checks/sortOrder.js
The `sortOrder()` function appears to make an assumption about custom
sort functions that isn't true in the V8 shipped with Node.js 11. As a
result, tests fail in Node.js 11, and probably code in the wild fails
too. This fixes the function to be compatible with Node.js 11.
This will also mean that Travis should now start passing again.
> Fix for Node.js 11

- src/core/cache.js
Remove the declaration of 'path' in the 'cache.js', due to a warning
when running `npm run test`：
> Fix：Remove useless `path` reference

- package.json
- test/test.js
Update dev dependencies:
* istanbul 0.4.3 -> 0.4.5
* jsdoc 3.4.2 -> 3.6.2
* mocha 2.5.3 -> 6.1.4
Update dependency:
* chokidar 1.5.2 -> 3.0.2
The mocha udpate required a small change to the test file as mocha no
longer forces an exit once all tests have passed. So a file had to be
unwatched after the relevant test passed, or otherwise mocha would not
exit.
These updates resolve all warnings from `npm audit` on a fresh clone of the repository.
> chore: Update various dependencies
